openapi: 3.0.0
info:
  title: API de Monitoramento de Anomalias
  description: API para detectar anomalias em dados de sensores usando KNN e Mahalanobis
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Servidor local
paths:
  /:
    get:
      summary: Página inicial da API
      responses:
        '200':
          description: Resposta de sucesso
  /predict:
    post:
      summary: Prever anomalias nos dados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dados:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
      responses:
        '200':
          description: Retorno das previsões
          content:
            application/json:
              schema:
                type: object
                properties:
                  dist_mahalanobis:
                    type: array
                    items:
                      type: number
                  eh_anomalia_mahalanobis:
                    type: array
                    items:
                      type: boolean
                  resultado_knn:
                    type: array
                    items:
                      type: integer
                  eh_anomalia_knn:
                    type: array
                    items:
                      type: boolean
  /collect:
    post:
      summary: Coletar dados do sensor para armazenamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dados:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
      responses:
        '200':
          description: Confirmação do armazenamento dos dados
  /predict_knn:
    post:
      summary: Prever anomalias usando KNN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dados:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
      responses:
        '200':
          description: Retorno da previsão KNN
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado_knn:
                    type: array
                    items:
                      type: integer